name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  host-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install clang llvm libelf1 libelf-dev zlib1g-dev
    - name: Install bpftool
      run: |
          git clone -q https://github.com/libbpf/bpftool.git
          pushd bpftool; git submodule update --init
          pushd src; make; sudo make install;
          popd; popd
    - name: Build
      run: make
    - name: Run tests
      run: .ci/strace-test.sh

  host-x86-cross-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install clang llvm libelf1 libelf-dev zlib1g-dev dwarves gcc-aarch64-linux-gnu help2man libtool-bin autopoint
          rustup target add aarch64-unknown-linux-gnu
    - name: Install bpftool
      run: |
          git clone -q https://github.com/libbpf/bpftool.git
          pushd bpftool; git submodule update --init
          pushd src; make; sudo make install;
          popd; popd
    - name: Install arm64 toolchains
      env:
          KERNEL_VER: 7.0.1
      run: .ci/install-arm64-toolchains.sh

    - name: Build
      run: |
          export PATH=$PATH:/usr/local/aarch64-none-linux-gnu/bin/
          VMLINUX=linux-7.0.1/vmlinux make ARCH=aarch64 CROSS_COMPILE=aarch64-none-linux-gnu- build
